name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        apt-get update && apt-get -y upgrade
        python -m pip install --upgrade pip
        pip install pylint
        apt-get -y install python3-dev default-libmysqlclient-dev build-essential
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
